### ISSUE TITLE
Explanation for dummies like me

### ISSUE THREAD

**Issue by susannaanas** [timwaters/warper_oauth_token_auth_demo#1]
Hi

Writing a blog post and would like to introduce the new authentication method and this tool. Could you explain it to dummies?

**Comment by timwaters** [comment]
This repository is served a website or via github pages: http://timwaters.github.io/warper_oauth_token_auth_demo/

The user clicks to authenticate with the wikimaps warper (or github) via wikimedia commons

the user can then get their user details via the new API which is needs to be authenticated,

the user can get map details from the API which doesnt need to be authenticated

The user can log out and try the above calls again

![screenshot - 040816 - 14 02 00](https://cloud.githubusercontent.com/assets/48941/17402666/4a859282-5a4c-11e6-8c6b-f931aba93d5a.png)

![screenshot - 040816 - 14 03 18](https://cloud.githubusercontent.com/assets/48941/17402665/4a839022-5a4c-11e6-9649-505260180918.png)
